### ISSUE TITLE
Mismatch between numpy and pandas

### ISSUE THREAD

**Issue by 02hyc** [microsoft/SeqSNN#19]
Hi team,
Great work first of all. I tried to run the experiment and create an env with py=3.10, and follow the README to run `pip install -e .` to install the environment. However, when I tried to run the training with `python -m SeqSNN.entry.tsforecast exp/forecast/ispikformer/ispikformer_electricity.yml`, it failed with the log below:
```terminal
/opt/conda/envs/SeqSNN/lib/python3.10/site-packages/utilsd/experiment.py:16: UserWarning: PyTorch is not installed. Some features of utilsd might not work.
  warnings.warn('PyTorch is not installed. Some features of utilsd might not work.')
Traceback (most recent call last):
  File "/opt/conda/envs/SeqSNN/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/SeqSNN/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/storage/huangyanchen/SeqSNN/SeqSNN/SeqSNN/entry/tsforecast.py", line 7, in <module>
    from SeqSNN.dataset import DATASETS
  File "/storage/huangyanchen/SeqSNN/SeqSNN/SeqSNN/dataset/__init__.py", line 1, in <module>
    from .ts import TSDataset
  File "/storage/huangyanchen/SeqSNN/SeqSNN/SeqSNN/dataset/ts.py", line 9, in <module>
    import pandas as pd
  File "/opt/conda/envs/SeqSNN/lib/python3.10/site-packages/pandas/__init__.py", line 46, in <module>
    from pandas.core.api import (
  File "/opt/conda/envs/SeqSNN/lib/python3.10/site-packages/pandas/core/api.py", line 1, in <module>
    from pandas._libs import (
  File "/opt/conda/envs/SeqSNN/lib/python3.10/site-packages/pandas/_libs/__init__.py", line 18, in <module>
    from pandas._libs.interval import Interval
  File "interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```
I tried to fix it but it still has some mismatch between numpy and other packages. My platform is linux, hope you can help me, thanks!

**Comment by dfxue** [comment]
Hi, I have also encountered this problem. How did you solve it? Thank you very much.

**Comment by Lvchangze** [comment]
pip install numpy==1.26

**Comment by dfxue** [comment]
您好：    您发送的邮件已经收到。
